defaults:
  - _self_

name: RobosuiteDinosaur
env: RobosuiteSlotEnv

mode: "hard"
rew_type: "dense"
tags: "robosuite,dinosaur"

num_stacked_obss: 1
obs_size: 64
obs_channels: 3
max_steps: 1000
max_episode_steps: 125

from_pixels: true
warp_frame: true
gray_scale: false
scale: false
transform2string: false
observation_shape: [3, 224, 224]

oc_model: true
oc_model_type: DINOSAUR
num_slots: 5
slot_dim: 64
checkpoint_path: /opendilab/pretrained_encoders/robosuite.ckpt
model_name: vit_base_patch16_224_dino
input_feature_dim: 768
num_patches: 196
features: [2048, 2048, 2048]
